### PR TITLE
Curation for package with Coordinates(name=antlr, namespace=antlr, provider=mavencentral, type=maven).

### PR DESCRIPTION
**Pull request by clearlydefinedbot**
**Type:** Import

**Summary:**
Curation for package with Coordinates(name=antlr, namespace=antlr, provider=mavencentral, type=maven).

**Details:**
Imported from curation data of the [OSS Review Toolkit](https://github.com/heremaps/oss-review-toolkit) via the [clearly-defined](https://github.com/heremaps/oss-review-toolkit/tree/master/clearly-defined) module.

**Resolution:**
No comment.

**Affected definitions**:
- [antlr 2.7.7](https://clearlydefined.io/definitions/maven/mavencentral/antlr/antlr/2.7.7)

### CODE REVIEW

**Comment by pombredanne** [comment]
@sschuberth it would be great if you could provide comments about the curation
`Resolution: No comment.` is a tad terse?
In particular what are the facts you have used to update the declared license?
This is interesting in the light of this manual curation https://github.com/clearlydefined/curated-data/pull/2575 by @ariel11  and @capfei and how the two compare since https://github.com/clearlydefined/curated-data/pull/2575/files#diff-9fccdfbef9f0883bcb1f86e13d8d1b6bR1 is the same as here.

**Comment by sschuberth** [comment]
Yeah, the "No comment" strings are just replacements I had to do for now as some curations I'm testing with contain company-internal info in the comment file.

To be more precise what I'm ask for: For now, please don't review the diff of the curation. That's just test data. But I'm interesting on feedback on the texts contained in the first post of the conversation tab, and the PR title.

**Comment by jeffmcaffer** [comment]
This is awesome. A few feedback points
* type = import is a bit misleading. AFAIK ClearlyDefined does not have an import feature. This is a full on user supplied curation not the result of a mechanical process. The intent of `type` was to capture the nature of the curation, not the process or means by which it came. 
* would be great if the coordinates were shown in their normal form (e.g., maven/mavencentral/antlr/antlr

**Comment by sschuberth** [comment]
Thanks for the feedback @jeffmcaffer !

> The intent of `type` was to capture the nature of the curation, not the process or means by which it came.

But isn't the intent of a curation, well, always to curate broken meta-data? I'm really not trying to ridicule this; I'm simply having a hard time figuring out what could be meaningful values for `type` here. Would you have some examples?

Also, I tried to pick something generic as there is no such thing as a `type` for [curations in ORT format](https://github.com/heremaps/oss-review-toolkit/blob/ba5d1881af30ecaf48b5a35f4046cd865b6de82d/model/src/main/kotlin/PackageCurationData.kt#L33-L84), so I do not really have a way to automatically deduce one.

> would be great if the coordinates were shown in their normal form (e.g., maven/mavencentral/antlr/antlr

Will do that. Just wondering, do you have a name for that notions? Something like "ClearlyDefined coordinates"? So the general form seems to be `$type/$provider/$namespace/$name`, correct?

**Comment by jeffmcaffer** [comment]
You can see the types in the UI. I'm actually surprised that a value of `import` was accepted. Perhaps we are not checking the content of the PR....

image

In the end the type is more for reporting and conveying intent to the reviewers than anything else. As long as you use one of the values and it's reasonable, you should be good.

For the coordinates, see the doc at https://docs.clearlydefined.io/using-data for detail.

**Comment by sschuberth** [comment]
Thanks @jeffmcaffer, so how does this look instead: https://github.com/clearlydefined/curated-data-dev/pull/961

**Comment by jeffmcaffer** [comment]
Looks better thanks. What of this is autogenerated vs something that the curator would enter? That is, what is the user experience in ORT for deciding that the curation should be contributed and initiating that process?

**Comment by sschuberth** [comment]
Nothing of the diff is actually "autogenerated"; everything is based on curation data that was created by a human in ORT format, and then these human-created meta-data fields are mapped to the CD data model.

**Pull request closed without merging**
